apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosoknad-proxy
  namespace: flex
  labels:
    team: flex
spec:
  image: {{ image }}
  replicas:
    min: 4
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  ingresses:
    - "https://syfosoknad-proxy.dev.nav.no/"
  liveness:
    path: /isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 150m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
  accessPolicy:
    outbound:
      external:
        - host: api-gw-q1.oera.no
  envFrom:
    - secret: syfosoknad-gateway-api-gw-apikey
  env:
    - name: ALLOWED_ORIGINS
      value: "https://www-gcp.dev.nav.no,https://tjenester-q1.nav.no"
    - name: SERVICE_GATEWAY_URL
      value: "https://api-gw-q1.oera.no/syfosoknad"

