apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosoknad-proxy
  namespace: flex
  labels:
    team: flex
spec:
  image: {{ image }}
  replicas:
    min: 4
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  ingresses:
    - "https://syfosoknad-proxy.nav.no/"
  liveness:
    path: /isAlive
    initialDelay: 30
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 768Mi
  accessPolicy:
    outbound:
      external:
        - host: api-gw.oera.no
  envFrom:
    - secret: syfosoknad-gateway-api-gw-apikey
  env:
    - name: ALLOWED_ORIGINS
      value: "https://www.nav.no,https://tjenester.nav.no"
    - name: SERVICE_GATEWAY_URL
      value: "https://api-gw.oera.no/syfosoknad"

