apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{app}}
  namespace: flex
  labels:
    team: flex
spec:
  image: {{ image }}
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    cpuThresholdPercentage: 50
  port: 8080
  ingresses:
    - {{ingress}}
  liveness:
    path: /internal/isAlive
    initialDelay: 5
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 5
    periodSeconds: 5
    timeout: 5
    failureThreshold: 30
  resources:
    limits:
      cpu: 300m
      memory: 800Mi
    requests:
      cpu: 100m
      memory: 500Mi
  accessPolicy:
    outbound:
      {{#if externalHosts}}
      external:
      {{#each externalHosts as |url|}}
         - host: {{url}}
      {{/each}}
      {{/if}}
      {{#if outboundApplications}}
      rules:
      {{#each outboundApplications as |app|}}
         - application: {{app}}
      {{/each}}
      {{/if}}
  {{#if secrets}}
  envFrom:
  {{#each secrets as |secret|}}
    - secret: {{secret}}
  {{/each}}
  {{/if}}
  env:
  {{#each env}}
     - name: {{@key}}
       value: {{this}}
  {{/each}}

