server:
  port: 8080

spring :
  main.banner-mode: 'off'
  profiles:
    active: default

logging.config: "classpath:logback.xml"
auth.cookie.name: "selvbetjening-idtoken"
service.gateway.key: ""
allowed.origins: ""

no.warning.paths: "/,/metrics,/ads.txt,/robots.txt"
