server:
  port: 8080

spring :
  main.banner-mode: 'off'
  profiles:
    active: default

logging.config: "classpath:logback.xml"
auth.cookie.name: "selvbetjening-idtoken"
service.gateway.key: ""
allowed.origins: ""

no.warning.paths: "/,/ads.txt,/robots.txt"

service.liveness.path: "/is_alive"


management:
  endpoint.prometheus.enabled: true
  endpoints.web:
    base-path: /internal
    exposure.include: prometheus
    path-mapping.prometheus: /prometheus
