apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: spinnsyn-backend-veileder-proxy
  namespace: flex
  labels:
    team: flex
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  ingresses:
    - "https://spinnsyn-backend-veileder-proxy.dev.intern.nav.no/"
  liveness:
    path: /isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 20m
      memory: 50Mi
  accessPolicy:
    outbound:
      rules:
        - application: spinnsyn-backend
  env:
    - name: ALLOWED_ORIGINS
      value: "N/A"
    - name: SERVICE_GATEWAY_URL
      value: "http://spinnsyn-backend"
    - name: AUTH_COOKIE_NAME
      value: "isso-idtoken"

