apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: spinnsyn-backend-proxy
  namespace: flex
  labels:
    team: flex
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  ingresses:
    - "https://spinnsyn-backend-proxy.dev.nav.no/"
  liveness:
    path: /isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 768Mi
  accessPolicy:
    outbound:
      rules:
        - application: spinnsyn-backend
  env:
    - name: ALLOWED_ORIGINS
      value: "https://www-gcp.dev.nav.no,https://tjenester-q1.nav.no,https://flex-vedtak-mock.dev.nav.no"
    - name: SERVICE_GATEWAY_URL
      value: "http://spinnsyn-backend"

