name: Bygg flex-spring-proxy
on:
  push:
    paths:
      - flex-spring-proxy/**
      - .github/workflows/flex-spring-proxy.yml
env:
  APP: flex-spring-proxy
jobs:
  build:
    name: Bygg flex-spring-proxy
    runs-on: ubuntu-latest
    steps:
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '14'
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Generer versjon og image navn
        run: |
          TIME=$(TZ="Europe/Oslo" date +%Y.%m.%d-%H.%M)
          COMMIT=$(git rev-parse --short=8 HEAD)
          VERSION=$TIME-$COMMIT
          echo "IMAGE=docker.pkg.github.com/${GITHUB_REPOSITORY}/$APP:$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - run: echo $VERSION > VERSION.txt
      - name: Last opp VERSION til neste job
        uses: actions/upload-artifact@v2.2.3
        with:
          name: VERSION.txt
          path: VERSION.txt
      - name: Login to Github Package Registry
        env:
          DOCKER_USERNAME: x-access-token
          DOCKER_PASSWORD: ${{ secrets.ACCESS_TOKEN }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin docker.pkg.github.com
      - name: Bygg image
        run: |
          cd flex-spring-proxy
          mvn clean install
          docker build -t ${IMAGE} .
      - name: Push Docker image
        run: docker push ${IMAGE}
